# Generated by Django 5.2.1 on 2026-04-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_student_mobile_student_sms_sent"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=500)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="template_sent",
            field=models.BooleanField(default=False),
        ),
    ]
